name: consejo_seguro_mobile
version: 0.1.0
publish_to: 'none'
description: App mÃ³vil/PWA para ConsejoSeguro

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.0
  intl: ^0.19.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/arb/
